### ISSUE TITLE
Public user profiles

### ISSUE THREAD

**Issue by shelbys-dev** [Azuriom/Azuriom#173]
🇺🇸 Have the ability to view other users' profiles

🇫🇷 Avoir la possibilité de voir les profils des autres utilisateurs

**Comment by BrayaanPS** [comment]
If the public profiles option is to be added, more things should be added, e.g.
- Profile banner 
- [Upload profile image](https://github.com/Azuriom/Azuriom/issues/174) 
- In the profile will have a part where it says user information (profile views, last viewed, date of registration).
- Profile posts
Extra:
With the profile banner and upload profile image, should have permissions for its use, so that only some can have own images (not to fill our storage), for instead should have an option for those who do not have permissions choose a banner.
Example
![image](https://user-images.githubusercontent.com/30274810/177018411-66094b43-bbea-4e62-8cf6-7882a7c8746e.png)

This option would be for both profile and banner
_The upload option should only be seen by those who have permissions._
![image](https://user-images.githubusercontent.com/30274810/177018449-3997cefa-9928-4271-86f3-79b4ef1fc23a.png)
