### ISSUE TITLE
Revert/Select Theme Version to any release version.

### ISSUE THREAD

**Issue by 0xBitMC** [Azuriom/Azuriom#179]
Greetings,

Earlier today my Theme stated that I was able to update it, I did not want to update because I had made adjustments. Despite me not clicking update, the theme updated automatically, and I was unable to revert the theme back to the previous version. The current version of the theme is broken and does not allow for configuration options to be changed at this time. The developer of the theme is not available to update/bug fix, but this is service interrupting. 

This made me realize that some sort of function that will allow you to use any version of a theme would be a helpful feature. This would help for people in predicaments such as mine and need to move a version back.

**Comment by MrMicky-FR** [comment]
Hi,

I am not sure what’s caused your issue because there is no automatic updates of Azuriom or the extensions. You can take a look at the website logs in the admin panel to see who updated the theme. About this issue it’s more as an edge cas, as updates shouldn’t have these kind of issues. What’s the theme you are using ? I’ll try to see if I can revert the last update on the market
