### ISSUE TITLE
Alternative sign in or registration methods

### ISSUE THREAD

**Issue by WEEZOOKARP** [Azuriom/Azuriom#247]
### Description of your suggestion

For steam instances of azuriom it could be a nice feature to allow sign in through discord or for certain games like fivem, a cfx login prompt just like how txadmin does it.

### Advantages

more options for users to sign in, also allows for higher trust between users and admins as if you run azuriom on a vps you will most likely get pinged by steam and any user that attempts to sign in will be warned that the origin domain has been reported for fraudulent activity, even if the domain is just the server's ip.

**Comment by Dotta4You** [comment]
Good idea - Many signup/in options That can be enabled/disabled in azuriom :D

**Comment by MrMicky-FR** [comment]
Unfortunately this is not possible because for Steam games we need the Steam login to get the SteamID of the user, for ingame commands.

About CFX login, I can’t find any documentation or API endpoints to use for the login, but if someone can find something it would definitely be implemented !

**Comment by thefourcraft** [comment]
CFX login? Do you mean Cfx.re... 
and they don't have an API for login or any thing
I did ask them because it sound interesting  - https://forum.cfx.re/t/do-we-have-an-api-for-keymaster/4943885

**Comment by WEEZOOKARP** [comment]
yes i mean cfx re, and txadmin seems to be able to use it for auth
![image](https://user-images.githubusercontent.com/76672483/200156542-054c4568-54dd-4be2-81e6-c812a9a71210.png)

**Comment by Javdu10** [comment]
I remember when the login for steam was implemented, it was forced the way it is by an admin that is not even around anymore. Without taking into consideration the rest of users or different use cases that could emerge with multiple ways to sign in.

Why is it like that? "Because it's like this on other websites" 

If more thought were given to that "multiple ways to sign in" we could come up with "Requirements" that needs to be filled in before an action like "You need to link your steam account for this purchase, click here" that kind of flow...
