### ISSUE TITLE
Register with Facebook, Google etc API

### ISSUE THREAD

**Issue by n0tMarvin** [Azuriom/Azuriom#253]
### Description of your suggestion

Implent the API‘s to make it possible to sign up with your FB, Google or whatever account

**Comment by MrMicky-FR** [comment]
Not possible, see #247

**Comment by n0tMarvin** [comment]
If you are against every single good Suggestion then dont take any suggestion at all. We can stop bothering then to make this cms even better jesus god

**Comment by MrMicky-FR** [comment]
And I’m not against all suggestions, just see the amount of implemented suggestions if you doubt. 

Also note that it’s not simple as « this website has it », because when adding a feature into Azuriom it should be compatible with _all_ games (or at least not just one). I don’t know how Flyff works exactly, but as I said for Steam games and Minecraft (premium + bedrock), this isn’t possible because Discord/Google/etc doesn’t provide the game ID (SteamID, UUID or XUID), which is required for many commands, so how on earth the website should guess the game id if it isn’t provided by the login provider (Google/Discord/etc doesn’t have your SteamID or whatever)

**Comment by thefourcraft** [comment]
@n0tMarvin https://universe.flyff.com/ is a community that invested a lot of coding time in the website, 
and Azuriom is free, other alternatives charge you money. if you want something you can pay for a developer on fiver or contact other community developers they might help you if you pay them

it's not cool to disrespect OSS projects that actually make good things
