### ISSUE TITLE
Unable to login with cfx in FiveM

### ISSUE THREAD

**Issue by Ventrex** [Azuriom/Azuriom#415]
### Bug description

When you create a new and empty website for FiveM only the person who created the website can login.
We tried to use an other username during the installation and even with that username we where unable to login.
Only the person who installed the azuriom webpage can login.
When you try to login via the new login method (since the update of 05-12-2023) this issue exists.

### Step to reproduce

- Create a new website
- Login with an other username in cfx (not yourself otherwise it will “work”, not really)
- login with own cfx or other cfx (not the same as used during installation) 
- Looks like the cache or something from cfx local is used, not the one you fill in. But others cannot login because if this. Only 1 person can login. The creator.
- logs is empty
![image](https://github.com/Azuriom/Azuriom/assets/29728210/c6c0301a-edbc-4584-b8ab-31d553278b95)

### Errors / Logs

Oops

The software powering this discussion forum encountered an unexpected problem. We apologize for the inconvenience.

Detailed information about the error was logged, and an automatic notification generated. We'll take a look at it.

No further action is necessary. However, if the error condition persists, you can provide additional detail, including steps to reproduce the error, by posting a discussion topic in the site's feedback category.

### Web server

Nginx

### Database type

MySQL

### PHP version

8.1

**Comment by MrMicky-FR** [comment]
The problem is that Discourse (the forum system used by Cfx) requires the `client_id` to be unique for each user. However, Azuriom has no way of knowing whether the user has already logged on to the site before the user is logged in.

Also, using a different `client_id` for each connection would result in a new authorized application appearing each time in the user profile on Cfx.re, which would not be viable.

Until we have a better solution, we reverted the authentication for FiveM to Steam. This does not affect compatibility with AzLink.

**Comment by Poseidon281** [comment]
How ever when i download the newest version of yesterday it is still via CFX Login. Did you just change this? Do i need to download the newest version or was this changest like a few days ( or more) ago?

**Comment by MrMicky-FR** [comment]
Yes just changed it 5 minutes ago, the new version (1.1.8) will be released shortly
