### ISSUE TITLE
Add a script for the caddy web server to the documentation

### ISSUE THREAD

**Issue by Zeith22** [Azuriom/Azuriom#443]
### Description of your suggestion

I propose to add instructions on how to install Azuriom on the Caddy web server because Caddy itself is very simple, fast and easy to use, and because of its simplicity, more ordinary administrators will be able to install Azuriom on their own servers without any problems.

### Advantages

Easy to use by Administrators without experience and knowledge
Automatic configuration of HTTPS with Let's Encrypt that Apache2 and NGINX do not have
Performance on par with NGINX or (possibly) better

**Comment by MrMicky-FR** [comment]
The goal of the Azuriom documentation is not to provide an extensive list of all available web servers, but only to provide an easy start for using Azuriom.

As for Caddy, since Azuriom doesn't have any specific requirements compared to Laravel, any online guide for deploying a Laravel application on Caddy should work perfectly.
