### ISSUE TITLE
Cant add server [FiveM] Issue

### ISSUE THREAD

**Issue by exotic-6666** [Azuriom/Azuriom#88]
When i go into the admin panel and add my server it doesnt want to i dont know why it does this

**Comment by Javdu10** [comment]
Hi @exoticwastaken, please provide more information, like the error, what you tried etc. We cannot help you if you don't give any information. 

Make sure you port are correct and reachable.
Cheers

**Comment by exoticwastaken** [comment]
![image](https://user-images.githubusercontent.com/68249812/131570303-25a76ef9-95e2-4300-8bd6-e6af24a4b6af.png)

**Comment by Javdu10** [comment]
@exoticwastaken can you connect to your server with another tool and issue RCON commands?

**Comment by bedar89** [comment]
I can confirm I have the same issue. There isn't a lot of information to share. I've tried both with FiveM Status and FiveM RCON option. I can confirm that I'm able to connect with IceCon to my server.
![image](https://user-images.githubusercontent.com/2621954/132476239-2643ecae-314a-4491-ae40-260bee760ede.png)

**Comment by Javdu10** [comment]
Hi, if any of you @bedar89 and @exoticwastaken have some codding skills is it possible that you check these files?

- [FiveMStatus.php](https://github.com/Azuriom/Azuriom/blob/master/app/Games/Steam/Servers/FiveMStatus.php) 
- [FiveMRcon.php](https://github.com/Azuriom/Azuriom/blob/master/app/Games/Steam/Servers/FiveMRcon.php) with the RCON implementation here: [/Protocol/FiveMRcon.php](https://github.com/Azuriom/Azuriom/blob/master/app/Games/Steam/Servers/Protocol/FiveMRcon.php)

I'm personally not familiar with FiveM so I cannot really help you here but if you can connect with another tool, then the problem lies in these files

Thank you!

**Comment by MrMicky-FR** [comment]
Hi,

Sorry for the late reply, after some testing I can't reproduce this issue, I tested with many random servers from a FiveM server list and it works fine with FiveM status: 
![](https://user-images.githubusercontent.com/30863452/151886092-0da4ee54-6a93-440a-ae26-42e93672b153.png)

If you still have this issue, can send the address of the FiveM server here or on DM on [Discord](https://azuriom.com/discord) ?

I will also improve the error message in the next update, maybe it can help.
